services:
  - type: web
    name: sod-2025-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.12
    disk:
      name: uploads
      mountPath: /app/static
      sizeGB: 1 