"""Add is_archived field to Registration model

Revision ID: 17b33b2559ab
Revises: 072e4c2586ff
Create Date: 2025-03-03 21:38:10.058818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b33b2559ab'
down_revision = '072e4c2586ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
