"""Add checked_in_by to CheckIn model

Revision ID: 072e4c2586ff
Revises: 2239b53fec3c
Create Date: 2025-03-03 20:33:10.860035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072e4c2586ff'
down_revision = '2239b53fec3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_check_ins_admin', 'admins', ['checked_in_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_constraint('fk_check_ins_admin', type_='foreignkey')
        batch_op.drop_column('checked_in_by')

    # ### end Alembic commands ###
